### ISSUE TITLE
知乎是不是流程还没走通，看代码中知乎的配置文件是空的，代码中流程也不完整？

### ISSUE THREAD

**Issue by bailiangjin** [ddean2009/blog-auto-publishing-tools#3]
如题，知乎是不是流程还没走通，看代码中知乎的配置文件是空的，代码中流程也不完整？

**Comment by ddean2009** [comment]
知乎基本流程是通的，还要再完善一下， 这几天会出个完善版本。

**Comment by bailiangjin** [comment]
> 知乎基本流程是通的，还要再完善一下， 这几天会出个完善版本。

试了一下，文章发布流程走不通，必须手动选择标签之后才能发布，尝试了下添加输入选择标签的逻辑没成功，还望大佬及时搞定

**Comment by ddean2009** [comment]
已解决。
